Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-18.04"

  config.vm.provider "virtualbox" do |vb|
    vb.name = "vmpostgres"
    vb.memory = "4096"
    vb.cpus = 2
  end

  config.vm.hostname = "vmpostgres"

  config.vm.provision "file", source: "/home/alex/SkillFactory/sf_practice/6/empty_file", destination: "$HOME/empty_file"
  
  config.vm.provision "shell", path: "provision.sh"
end